// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using Core.ViewModels;
using FFImageLoading.Cross;
using Foundation;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Platforms.Ios.Views;
using UIKit;

namespace MvvmExampleiOS.Views
{
    [MvxFromStoryboard("Main")]
    public partial class DetailViewController : MvxViewController<DetailViewModel>
	{
        //private MvxCachedImageView _imageControl;

        public DetailViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            //var imageViewLoader = new MvxCachedImageView.ImageSourceBindi;
            base.ViewDidLoad();
            var set = CreateBindingSet();
            set.Bind(cityNameLabel).To(m => m.SelectedWeatherResult.Name);
            set.Bind(countryLabel).To(m => m.SelectedWeatherResult.Sys.Country);
            set.Bind(weatherLabel).To(m => m.SelectedWeatherResult.Weather[0].Main);
            set.Bind(currentTempLabel).To(m => m.SelectedWeatherResult.Main.Temp);
            set.Bind(minTempLabel).To(m => m.SelectedWeatherResult.Main.TempMin);
            set.Bind(maxTempLabel).To(m => m.SelectedWeatherResult.Main.TempMax);
            set.Bind(mvxImageView).For(v => v.ImagePath).To(m => m.ImageUrl);
            
            //set.Bind(imageViewLoader).To(m => m.SelectedWeatherResult.Weather[0].Icon).WithConversion("StringUrl");
            set.Apply();
        }

    }
}
