// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Binding.Views;
using MvvmCross.Platforms.Ios.Views;
using MvvmExampleiOS.Views.Cells;
using UIKit;

namespace MvvmExampleiOS.Views
{
    [MvxFromStoryboard("Main")]
    public partial class ListExampleViewController : MvxViewController<ListViewModel>
    {
		public ListExampleViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var source = new MvxSimpleTableViewSource(dataTableView, "MyTableViewCell", MyTableViewCell.Key);
            dataTableView.RowHeight = 130;

            var set = this.CreateBindingSet<ListExampleViewController, ListViewModel>();
            set.Bind(source).For(v => v.ItemsSource).To(vm => vm.People);
            set.Apply();

            dataTableView.Source = source;
            dataTableView.ReloadData();
        }
    }
}
